# Begin: Configmap
apiVersion: v1
kind: ConfigMap
metadata:
  name: mariadb-deployment-init-configmap
data:
  mariadb-init.sql: |
    SET GLOBAL sql_mode = 'ANSI_QUOTES';

    CREATE TABLE `songs` (
      `song` VARCHAR(30) NOT NULL,
      `link`  VARCHAR(500),
      `band` VARCHAR(50),
      PRIMARY KEY (`song`)
    );

    CREATE TABLE `popular` (
      `song` VARCHAR(30) NOT NULL,
      `count` BIGINT DEFAULT 0,
       PRIMARY KEY (`song`)
    );

    INSERT INTO songs (song, link, band) VALUES ('Doing It To Death', '/DoingItToDeath.mp4', 'The Kills');
    INSERT INTO songs (song, link, band) VALUES ('Breezeblocks', '/Breezeblocks.mp4', 'alt-J');
    INSERT INTO songs (song, link, band) VALUES ('The Adults Are Talking', '/TheAdultsAreTalking.mp4', 'The Strokes');
    INSERT INTO songs (song, link, band) VALUES ('Square Hammer', '/SquareHammer.mp4', 'Ghost');
    INSERT INTO songs (song, link, band) VALUES ('Circle With Me', '/CircleWithMe.mp4', 'Spiritbox');

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb-deployment
  labels:
    app: my-mariadb-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-mariadb
  template:
    metadata:
      labels:
        app: my-mariadb
    spec:
      # Mount the configmap volume
      # This is an excerpt of deployment.spec.template.spec
      volumes:
        - name: init-volume
          configMap:
            name: mariadb-deployment-init-configmap
      containers:
        - name: my-mariadb
          image: mariadb
          volumeMounts:
            - name: init-volume
              mountPath: /docker-entrypoint-initdb.d/
          # Set required environment variables to initialize the container
          env:
            - name: MARIADB_ROOT_PASSWORD
              value: "mysecretpw"
            - name: MARIADB_DATABASE
              value: "popular"
          ports:
            - containerPort: 3306

---
#Begin: Service
apiVersion: v1
kind: Service
metadata:
  name: my-app-mariadb-service
spec:
  selector:
    app: my-mariadb
  ports:
    - name: mariadb-proto
      protocol: TCP
      port: 3306
      targetPort: 3306
#End: Service